
#JDBC_CONNECTION "(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=$DB_HOST)(PORT=$DB_PORT))(CONNECT_DATA=(SID=$TWO_TASK)))" \
#JDBCCON="(DESCRIPTION="`tnsping $TWO_TASK 2 | grep "ADDRESS" | cut -c23-100`"(CONNECT_DATA=(SID=$TWO_TASK)))"

JDBCCON="(DESCRIPTION="`tnsping $TWO_TASK 2 | grep "ADDRESS" | cut -c36-116`"(CONNECT_DATA=(SERVICE_NAME=$TWO_TASK)))"
echo $JDBCCON 
export JDBCCON


java oracle.apps.xdo.oa.util.XDOLoader \
UPLOAD \
-DB_USERNAME apps \
-DB_PASSWORD uatapps1 \
-JDBC_CONNECTION $JDBCCON \
-LOB_TYPE TEMPLATE \
-APPS_SHORT_NAME XXERG \
-LOB_CODE XXERG_OE_PREPAYINV \
-LANGUAGE en \
-TERRITORY US \
-XDO_FILE_TYPE RTF \
-FILE_CONTENT_TYPE 'aplication/rtf' \
-FILE_NAME $XXERG_TOP/data/XXERG_OE_PREPAID_INVOICE.rtf \

java oracle.apps.xdo.oa.util.XDOLoader \
UPLOAD \
-DB_USERNAME apps \
-DB_PASSWORD $APPS_PASSWORD \
-JDBC_CONNECTION $JDBCCON \
-LOB_TYPE TEMPLATE \
-APPS_SHORT_NAME XXERG \
-LOB_CODE XXERG_AR_RAXINV_SEL \
-LANGUAGE en \
-TERRITORY US \
-XDO_FILE_TYPE RTF \
-FILE_CONTENT_TYPE 'aplication/rtf' \
-FILE_NAME $XXERG_TOP/data/XXERG_AR_INVOICE_PRINT.rtf \

java oracle.apps.xdo.oa.util.XDOLoader \
UPLOAD \
-DB_USERNAME apps \
-DB_PASSWORD $APPS_PASSWORD \
-JDBC_CONNECTION $JDBCCON \
-LOB_TYPE TEMPLATE \
-APPS_SHORT_NAME XXERG \
-LOB_CODE XXERG_SALES_ORDER_CONF \
-LANGUAGE en \
-TERRITORY US \
-XDO_FILE_TYPE RTF \
-FILE_CONTENT_TYPE 'aplication/rtf' \
-FILE_NAME $XXERG_TOP/data/XXERG_SALES_ORDER_CONF.rtf 
